name: Lint and Format Check (Changed Files Only)

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get list of changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.js
            **/*.md

      - name: Run ESLint on changed files
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          echo "Linting changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          npx eslint --max-warnings=0 --no-ignore --ext .js,.md ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run Prettier check on changed files
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          echo "Checking formatting on changed files..."
          npx prettier --check ${{ steps.changed-files.outputs.all_changed_files }}
